
edition = "2021"
format_strings = true
imports_layout = "HorizontalVertical"
max_width = 120
imports_granularity = "Crate"
normalize_comments = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
version = "Two"