[package]
name = "aleo-pool-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#snarkvm = { path = "../../src/snarkVM" }
snarkvm = { git = "https://github.com/HarukaMa/snarkVM.git", rev = "6812908b" }
snarkvm-algorithms = { git = "https://github.com/HarukaMa/snarkVM.git", rev = "6812908b" }
#snarkos = { path = "../../src/snarkOS" }
#snarkos-storage = { path = "../../src/snarkOS/storage" }
snarkos = { git = "https://github.com/HarukaMa/snarkOS.git", rev = "66140d4b" }
snarkos-storage = { git = "https://github.com/HarukaMa/snarkOS.git", rev = "66140d4b" }
structopt = "0.3.26"
tracing = "0.1.29"
tracing-log = "0.1.2"
tracing-subscriber = "0.3.8"
futures = "0.3.19"
futures-util = "0.3.19"
rand = "0.8.4"
tokio-util = "0.6.9"
tokio-stream = "0.1.8"
dirs = "4.0.0"
bincode = "1.3.3"
serde_json = "1.0.78"
anyhow = "1.0.53"
signal-hook = "0.3.13"
bytes = "1.1.0"
byteorder = "1.4.3"
warp = "0.3.2"

[dependencies.reqwest]
version = "0.11.9"
features = ["json"]

[dependencies.parking_lot]
version = "0.12.0"
features = ["serde"]

[dependencies.serde]
version = "1.0.136"
features = ["rc"]

[dependencies.tokio]
version = "1.16.1"
features = [
    "rt-multi-thread",
    "macros",
    "sync"
]

[dependencies.rocksdb]
version = "0.17.0"
default-features = false
features = ["zstd"]

[dependencies.signal-hook-tokio]
version = "0.3.1"
features = ["futures-v0_3"]

[profile.dev]
opt-level = 1
debug-assertions = false

[profile.release]
opt-level = 3
debug = 1
lto = "thin"
incremental = true
codegen-units = 256
