[package]
name = "aleo-pool-server"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#snarkvm = { path = "../../src/snarkVM" }
snarkvm = "0.8.0"
snarkvm-algorithms = "0.8.0"
#snarkos = { path = "../../src/snarkOS" }
#snarkos-storage = { path = "../../src/snarkOS/storage" }
snarkos = { git = "https://github.com/HarukaMa/snarkOS.git", rev = "f3cab7ee" }
snarkos-storage = { git = "https://github.com/HarukaMa/snarkOS.git", rev = "f3cab7ee" }
structopt = "0.3.26"
tracing = "0.1.31"
tracing-log = "0.1.2"
tracing-subscriber = "0.3.9"
futures = "0.3.21"
futures-util = "0.3.21"
rand = "0.8.5"
tokio-util = "0.7.0"
tokio-stream = "0.1.8"
dirs = "4.0.0"
bincode = "1.3.3"
anyhow = "1.0.55"
signal-hook = "0.3.13"
bytes = "1.1.0"
byteorder = "1.4.3"
warp = "0.3.2"

[dependencies.reqwest]
version = "0.11.9"
features = ["json"]

[dependencies.parking_lot]
version = "0.12.0"
features = ["serde"]

[dependencies.serde]
version = "1.0.136"
features = ["rc"]

[dependencies.serde_json]
version = "1.0.79"
features = ["preserve_order"]

[dependencies.tokio]
version = "1.17.0"
features = [
    "rt-multi-thread",
    "macros",
    "sync"
]

[dependencies.rocksdb]
version = "0.18.0"
default-features = false
features = ["zstd"]

[dependencies.signal-hook-tokio]
version = "0.3.1"
features = ["futures-v0_3"]

[profile.dev]
opt-level = 1
debug-assertions = false

[profile.release]
opt-level = 3
debug = 1
lto = "thin"
incremental = true
codegen-units = 256
