[package]
name = "aleo-pool-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#snarkvm = { path = "../../src/snarkVM" }
snarkvm = { git = "https://github.com/HarukaMa/snarkVM.git", rev = "6812908b" }
snarkos = { path = "../../src/snarkOS" }
snarkos-storage = { path = "../../src/snarkOS/storage" }
#snarkos = { git = "https://github.com/HarukaMa/snarkOS.git", rev = "53a22610" }
#snarkos-storage = { git = "https://github.com/HarukaMa/snarkOS.git", rev = "53a22610" }
structopt = "0.3.26"
tracing = "0.1.29"
tracing-subscriber = "0.3.7"
futures = "0.3.19"
futures-util = "0.3.19"
rand = "0.8.4"
tokio-util = "0.6.9"
tokio-stream = "0.1.8"
dirs = "4.0.0"
bincode = "1.3.3"
serde = "1.0.136"
anyhow = "1.0.53"
signal-hook = "0.3.13"
bytes = "1.1.0"
byteorder = "1.4.3"

[dependencies.tokio]
version = "1.16.1"
features = [
    "rt-multi-thread",
    "macros",
    "sync"
]

[dependencies.rocksdb]
version = "0.17.0"
default-features = false
features = ["zstd"]

[dependencies.signal-hook-tokio]
version = "0.3.1"
features = ["futures-v0_3"]